services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    volumes:
      - ./elastic:/var/lib/postgresql/data

  etl:
    build: postgres_to_es
    volumes:
      - ./postgres_to_es:/code
    depends_on:
      - db
      - es

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  app:
    build: .
    volumes:
      - ./src:/code
    ports:
      - '8000:8000'
    depends_on:
#      - es
      - redis