FROM python:3.9.0-slim-buster

RUN apt-get update && apt-get install build-essential -y

WORKDIR /src
COPY ./requirements.txt /src
COPY entrypoint.sh /usr/local/bin

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
#RUN pip install fastapi-admin

#COPY ./src /src
ENTRYPOINT ["sh", "/usr/local/bin/entrypoint.sh"]
