version: '3'

services:
  es:
    image: elasticsearch:7.7.0
    container_name: es
    volumes:
    - es-data:/usr/share/elasticsearch/data
    environment:
    - discovery.type=single-node
    ports:
    - "9200:9200"

volumes:
  es-data:
