version: '3'

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  es:
    image: elasticsearch:7.7.0
    container_name: es
    volumes:
    - es-data:/usr/share/elasticsearch/data
    environment:
    - discovery.type=single-node
    ports:
    - "9200:9200"

  postgres_4:
    image: postgres:13
    build: ./postgres
    container_name: postgres-4
    user: postgres
    env_file:
      - .env
    expose:
      - 5432
    volumes:
    - acc-db:/var/lib/postgresql/data


volumes:
  es-data:
  cache:
  acc-db: