version: '3'

services:
  postgres_4:
    image: postgres:13
    build: ./postgres
    container_name: postgres-4
    user: postgres
    env_file:
      - .env
    expose:
      - 5432
    volumes:
    - acc-db:/var/lib/postgresql/data

volumes:
  acc-db:
